server:
  port: 8322
spring:
  ai:
    # Key分享自：https://pgthinker.me/2023/10/03/196/
    baichuan:
      chat:
        enabled: true
        api-key: sk-131857011ab0b02f0a7439652c209f8e
        base-url: https://api.baichuan-ai.com
